### PR TITLE
Update "Vaccination series not valid" error text 

### PR DESCRIPTION
**Pull request by mickohanlon23**
Addresses [DVCI-235](https://jira.mitre.org/browse/DVCI-235). Open to changing the wording of the error message if people have suggestions. 

Here is a QR Code that should trigger this error message:
image

### CODE REVIEW

**Review by sarahmcdougall — APPROVED** [review]
Tested with the provided QR code and the new error message appears. Tested with several other QR codes and functionality remained as expected. I think the phrasing of the error message is good!

**Review by nkarip — CHANGES_REQUESTED** [review]
This is something that requires elaboration and cannot be explained with a single line. I would make the text "Vaccination status undetermined" with a more info icon that allows us to include more detail on what both valid and invalid mean. This can be a popover.

**Comment by mickohanlon23** [comment]
Updated "Vaccination Series Not Valid" text to be more descriptive, in response to @radamson's comment. Added an FAQ link to a static markdown file in our repository - we can update this link to point to an actual FAQ page in [DVCI-256](https://jira.mitre.org/browse/DVCI-256).

**Review by nkarip — CHANGES_REQUESTED** [review]
The markdown link does not work, get a 404. Any static page linked in the site should be placed in the public folder and should use a relative link, not absolute. Also, the text is too long and not accurate. We're not assessing "fully vaccinated" only primary vaccine series. People who have not had a booster would be get a pass but would not be considered "fully vaccinated" according to the CDC. This is why we should use a short comment here like "Cannot determine vaccination status" and put all the caveats in a FAQ instead.

**Comment by mickohanlon23** [comment]
> The markdown link does not work, get a 404. Any static page linked in the site should be placed in the public folder and should use a relative link, not absolute. Also, the text is too long and not accurate. We're not assessing "fully vaccinated" only primary vaccine series. People who have not had a booster would be get a pass but would not be considered "fully vaccinated" according to the CDC. This is why we should use a short comment here like "Cannot determine vaccination status" and put all the caveats in a FAQ instead.

@nkarip The link was meant merely as a placeholder, since we discussed creating the actual FAQ page in [DVCI-256](https://jira.mitre.org/browse/DVCI-256). It should link to an actual markdown file in our GitHub repository once this branched is merged into main, although it will change to point to an actual page in our site once the FAQ page exists. I agree it looks a bit silly having a link that doesn't actually direct anywhere useful, so I would be happy holding off on linking to the FAQ until it actual exists, if you want me to remove it.

As for the text, I agree that the shorter version is better. I'll go ahead and change to "Cannot determine vaccination status", and any further detail can be explained in the FAQ.

**Comment by nkarip** [comment]
Updated text looks good.

**Review by nkarip — APPROVED** [review]

**Pull request merged**
